# Generated by Django 4.2.6 on 2023-11-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='description',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='map_name',
            new_name='mapa',
        ),
    ]
