# Generated by Django 4.2.6 on 2023-11-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description_marker_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='mapa',
            field=models.IntegerField(),
        ),
    ]
