# Generated by Django 4.2.6 on 2023-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_marker_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='color',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
    ]
