# Generated by Django 4.2.6 on 2023-11-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
