# Generated by Django 4.2.6 on 2023-12-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_marker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='x',
            new_name='x_coordinate',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='y',
            new_name='y_coordinate',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='Tipo',
        ),
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
