# Generated by Django 4.2.6 on 2023-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_x_marker_x_coordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='mapa',
            field=models.TextField(),
        ),
    ]
