# Generated by Django 4.2.6 on 2023-12-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_marker_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='color',
        ),
        migrations.AddField(
            model_name='marker',
            name='tipo',
            field=models.TextField(default='normal'),
            preserve_default=False,
        ),
    ]
